site:
  name: RocketMQ
  site: 'https://sca.aliyun.com'
  base: '/'
  trailingSlash: 'always'
  websiteGithubUrl: 'https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/blob/develop-astro-sca'
  githubUrl: 'https://github.com/apache/rocketmq'
  logoUrl: "https://img.alicdn.com/imgextra/i1/O1CN01BRiD9Z1llvqUoupTm_!!6000000004860-2-tps-51-72.png"
  downloadEbooks: "https://developer.aliyun.com/ebook/7565?spm=a2c6h.20345107.ebook-index.55.63dd7863MiD2j0"

analytics:
  vendors:
    googleAnalytics:
      id: G-NP3B57ZGEF # or "G-XXXXXXXXXX"
    baiduAnalytics:
      id: 8d45b13e5afb579f4083ee89048f70ac
      verification: code-wzq5sw7io3
    aesAnalytics:
      pid: b3kPns
    clarityAlalytics:
      id: l4jzj6wbhh


# Default SEO metadata
metadata:
  title:
    default: AstroWind
    template: '%s — AstroWind'
  description: "\U0001F680 Suitable for Startups, Small Business, Sass Websites, Professional Portfolios, Marketing Websites, Landing Pages & Blogs."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AstroWind
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image


ui:
  colors:
    # 主按钮颜色，一般为主色中间的颜色，阿里橙色
    primary: "#FF6A00"
    # 次按钮的颜色，浅橙色
    secondary: "#FCF4EC" #moss-01
    # 强调色。"Header"中的联系我们
    accent: "#FFFBF7"
    # 中性色。作为大标题的字体颜色
    neutral: "#121314"
    # 基础色，用做首页的背景色1
    base-100: "#FFF"
    # header背景色
    base-header: "#F7F7F7"
    # footer背景色
    base-footer: "#EAEAEA"
    # Headline的上方小字选中
    info: "#0c0d10"
    # 成功。 Header的分割符、主要特性中的分割符、companiesfeedback中的isGray的背景颜色
    success: "#DDDEE4" #moss-08
    # 警告。header中的toggle-trigger-atc颜色
    warning: "#597371" #moss-10
    # 错误。搜索等组件的bgcolor
    error: "#EBEFEF" #moss-02
    # 静音 companiesfeedback中的isLight的背景颜色
    muted: "#FAE3CD" #green-03
    # 搜索/语言切换组件的文字颜色
    link: "#DDE4E4" #moss-03
    # 文章卡片的背景色
    card: "#F5F5F5"
    # 卡片标题的颜色&header字的颜色
    title: "#121316"
    # footer卡片的背景颜色
    footer: "#F7F0E8"
    # 卡片按钮的背景颜色
    card-btn: "#F4F4F6"
    # 标签选中颜色
    active:  "#FAFAFC"
    # 标签未选中颜色
    no-active:  "#5C6170"


